### ISSUE TITLE
TODO for release

### ISSUE THREAD

**Issue by 0xilly** [MinecraftForge/JavaWrapper#1]
- [x] Finish lzma decompressor
- [x] Launch launcher.jar from wrapper
- [x] Json parser
- [x] Make the wrapper work for installer jars
